### PR TITLE
Allow programmatic access to custom settings for MessageBus implementations

### PR DESCRIPTION
**Pull request by selimnairb**
This PR defines the method `getCustomSettings()` on the `MessageBus` interface, which allows the custom settings (and default values) relied on by `MessageBus` implementations to be discovered programmatically.  This will make it easier to integrate/validate configuration settings for future third-party implementations of `MessageBus`.

### CODE REVIEW

**Comment by hylkevds** [comment]
Is there a specific reason for not getting these settings directly from the CoreSettings store?

**Comment by selimnairb** [comment]
The use case here is for when creating CoreSettings programmatically, it is sometimes convenient to validate the options that can be set for a message bus implementation.

**Comment by hylkevds** [comment]
Ah, I see.
Might be useful for more than just the message bus...

**Comment by mjacoby** [comment]
We could think about extending this to not only get the current parameters and their values but e.g. also descriptions and valid values. Downside of this is, that it adds a non-neglectable amount of complexity for functionality that is not directly related to the core functionality of FROST server.

**Comment by selimnairb** [comment]
Yes, I wad thinking the same.  Perhaps for the persistence backends as well.  I can do another PR for that if you like.

**Pull request merged**
