### PR TITLE
Add JSON batch request extension

### PR DESCRIPTION
**Pull request by pbaumard**
multipart/mixed format is hard to generate and parse so I added a JSON batch request extension inspired by OData 4.01.

Note: Content-ID is now always output in case it was provided for multipart/mixed content, which conform with OData 4.0.

### CODE REVIEW

**Comment by hylkevds** [comment]
Thank you, easier-to-create batch content sounds good! :)
That's also something that will be of interest for V2 of the standard.

**Comment by pbaumard** [comment]
@hylkevds There is a weird reproducible side-effect with some MQTT test always failing:
checkSubscribeToEntitySetWithRelativeTopicUpdatePUT(de.fraunhofer.iosb.ilt.statests.c08mqttsubscribe.Capability8Tests).

I am struggling to fix it. Could you have a look?

**Comment by hylkevds** [comment]
Yes, I'll have a look.
If it's reproducible I should be able to find the problem.

**Comment by hylkevds** [comment]
Thanks again for the PR!
The build failure was not related to the PR, only exposed by it.

**Pull request merged**
