### PR TITLE
Re-implement programmatic access to MessageBus impl. default values i…

### PR DESCRIPTION
**Pull request by selimnairb**
I thought PR #82 was a bit clunky, so I re-implemented it in terms of annotations.  This has the benefit of providing semantic clarity that is applicable to FROST and to extensions of FROST.

### CODE REVIEW

**Comment by hylkevds** [comment]
Nice, that is a lot cleaner indeed!

**Comment by hylkevds** [comment]
I just realised a downside: It re-introduces "magic strings" that can not be checked at compile-time. Typing errors are easy to make, but hard to spot. Also, if a class changes a field name, the IDE can not update all references to it, and there are no compiler warnings...

Instead of passing the field name to `defaultValue` we could pass it the tag itself. The `ConfigDefaults` class can keep a cache of these for each class so it doesn't have to go through all fields for each call that requests a default value.

Or we should make each class that defines settings also define an `enum` with the keys and default values?

**Comment by hylkevds** [comment]
I've made a little example in branch settingsRefactor, introducing a `Setting` interface.

- MqttSettings uses this interface in an enum: [MqttSettings.java](https://github.com/FraunhoferIOSB/FROST-Server/blob/7c47abecec65de38e6e1bb50cd9a68dd427dcf9f/FROST-Server.Core/src/main/java/de/fraunhofer/iosb/ilt/sta/settings/MqttSettings.java)
- PersistenceSettings uses this interface in a simple implementation class: [PersistenceSettings.java](https://github.com/FraunhoferIOSB/FROST-Server/blob/7c47abecec65de38e6e1bb50cd9a68dd427dcf9f/FROST-Server.Core/src/main/java/de/fraunhofer/iosb/ilt/sta/settings/PersistenceSettings.java)

Of course, if we go this way, we could change the getters and setters in Settings to accept this interface instead of a key, and we could do away with the separate getters "with default", since the default comes in the Setting already.

What do you think?

**Comment by selimnairb** [comment]
> I just realised a downside: It re-introduces "magic strings" that can not be checked at compile-time. Typing errors are easy to make, but hard to spot. Also, if a class changes a field name, the IDE can not update all references to it, and there are no compiler warnings...
> 
> Instead of passing the field name to `defaultValue` we could pass it the tag itself. The `ConfigDefaults` class can keep a cache of these for each class so it doesn't have to go through all fields for each call that requests a default value.
> 
> Or we should make each class that defines settings also define an `enum` with the keys and default values?

See #86, which fixes the magic string problem.  However, the settingsRefactor approach is more comprehensive.  And I prefer the enum approach as it allows for iteration over all possible options without a priori knowledge of what the options are.  If you can merge #86, then merge the enum version of the settingsRefactor, I can refactor the MessageBus code to use the enums.

**Comment by selimnairb** [comment]
Okay, let me put a caching scheme in place so that this will be more performant during steady-state runtime.

**Pull request merged**
