### PR TITLE
new feature: set user defined ids

### PR DESCRIPTION
**Pull request by image357**
Adds user defined string ids for things and datastreams.
New module PGUserString is a copy of PGString with adjusted class/package/config names.

New class UserDefinedID handles processing of (json) entities to extract user ids.

PGUserString can default back to behavior of PGString via settings in class UserDefinedID:
* forcedefaultid
* allowdefaultid

### CODE REVIEW

**Comment by hylkevds** [comment]
Thanks for the PR.

Why the strange mechanism over the properties field? That seems like a very non-standard way to set an ID. Wouldn't it be better to just let the user directly specify the "@iot.id" in the Entity?

You only seem to allow user-specified IDs for Things and Datastreams, why is that?

**Comment by image357** [comment]
I've tested @iot.id now. It seems that one can also link locations etc. with @iot.id, not only create them.
Currently, sensors with @iot.id will fail if that id dosn't already exist.
Can this be made consistent and failsafe (no accidental linking/creation) across all entities?

**Comment by hylkevds** [comment]
> I've tested @iot.id now. It seems that one can also link locations etc. with @iot.id, not only create them.

Yes, that's described in the standard under 10.2.1.1 Link to existing entities when creating an entity

> Currently, for example sensors with @iot.id will fail if that id doesn't already exist.

Of course. If it finds an ID in a linked entity, it assumes it is an existing entity. If it does not find an ID, it assumes the user is doing a deep insert (10.2.1.2 Create related entities when creating an entity)

You'll have to add a third option: there is an ID, but the entity does not exist yet.

**Comment by hylkevds** [comment]
Do you not plan on working further on this?

**Comment by image357** [comment]
I will work further on this, probably planing to integrate it directly in PGString with some options for default behavior. I'll reopen the pull request when that feature is stable.

**Comment by hylkevds** [comment]
Great, thanks!

**Pull request closed without merging**
